version: '3'
services:
  riclibre:
    restart: always
    build: .
    image: riclibre:latest
    env_file:
      - ./.env
    volumes:
      - /var/www/riclibre/static:/var/www/static
      - /var/www/riclibre/media:/var/www/src/media/

    networks:
      riclibre-ntk:
        ipv4_address: 172.31.0.2

    depends_on:
      - db
      - redis
      - celery
      -  celery_beat

  celery:
    build: .
    command: celery -A riclibre worker -l info
    env_file:
      - ./.env
    volumes:
      - /var/www/riclibre/media:/var/www/src/media/
    depends_on:
      - db
      - redis
    networks:
      riclibre-ntk:
        ipv4_address: 172.31.0.5

  celery_beat:
    build: .
    command: celery -A riclibre beat -l info
    env_file:
      - ./.env
    volumes:
      - /var/www/riclibre/media:/var/www/src/media/
    depends_on:
      - db
      - redis
    networks:
      riclibre-ntk:
        ipv4_address: 172.31.0.6

  db:
    restart: always
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      riclibre-ntk:
        ipv4_address: 172.31.0.3

  redis:
    restart: always
    image: redis:latest
    networks:
      riclibre-ntk:
        ipv4_address: 172.31.0.4


networks:
  riclibre-ntk:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24


volumes:
  pgdata:
